image: node:8.11.2

cache:
  paths:
  - node_modules/

before_script:
  - npm install -g @angular/cli
  - npm install

lint-test:
  script:
      - npm run lint
      - cd pmweb && npm install
      - ng lint
