language: node_js

node_js:
  - "6.9"

cache:
  directories:
    - node_modules

before_script:
  - npm install -g @angular/cli

script:
  - npm run lint
  - cd pmweb && npm install tslint && ng lint
